In [1]:
##portfolio optimization

In [2]:
##portfolio optimization
##weight allocation for maximizing returns and reduce risks

In [3]:
#1.Visualise stock data, calculate percentage daily returns and analyze market trends
#2.Select a group of companies in a portfolio and perform portfolio analysis and visualization
#3.Run montecarlo simulations using random portfolio weights
#4.plot the risk vs return for each simulation run
#5.Select optimal portfolio weights that maximize return and reduce risks

In [4]:
import yfinance as yf

In [5]:
import pandas as pd
import numpy as np

In [6]:
import datetime as dt

In [7]:
stock_df=pd.read_csv('Amazon.csv')
stock_df.head(10)

        Date       Open       High        Low      Close     Volume  Adj Close
0   1/2/2018  58.599998  59.500000  58.525501  59.450500   53890000  59.450500
1   1/3/2018  59.415001  60.274502  59.415001  60.209999   62176000  60.209999
2   1/4/2018  60.250000  60.793499  60.233002  60.479500   60442000  60.479500
3   1/5/2018  60.875500  61.457001  60.500000  61.457001   70894000  61.457001
4   1/8/2018  61.799999  62.653999  61.601501  62.343498   85590000  62.343498
5   1/9/2018  62.845001  62.966499  62.088001  62.634998   73226000  62.634998
6  1/10/2018  62.257500  62.716499  61.861500  62.716499   53720000  62.716499
7  1/11/2018  62.987000  63.838501  62.823002  63.834000   62500000  63.834000
8  1/12/2018  63.669498  65.288002  63.669498  65.260002  108874000  65.260002
9  1/16/2018  66.150002  66.997002  64.614998  65.242996  144414000  65.242996

In [8]:
stock_df.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Volume       0
Adj Close    0
dtype: int64

In [9]:
stock_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1250 non-null   object
 1   Open       1250 non-null   float64
 2   High       1250 non-null   float64
 3   Low        1250 non-null   float64
 4   Close      1250 non-null   float64
 5   Volume     1250 non-null   int64
 6   Adj Close  1250 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 68.5+ KB

In [10]:
stock_df=pd.read_csv('JPM.csv')

In [11]:
stock_df.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [12]:
stock_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1368 entries, 0 to 1367
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1368 non-null   object
 1   Open       1368 non-null   float64
 2   High       1368 non-null   float64
 3   Low        1368 non-null   float64
 4   Close      1368 non-null   float64
 5   Adj Close  1368 non-null   float64
 6   Volume     1368 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 74.9+ KB

In [13]:
stock_df['Daily Returns']=stock_df['Adj Close'].pct_change(1)*100
stock_df

,Date,Open,High,Low,Close,Adj Close,Volume,Daily Returns
0,7/14/2017,90.809998,92.610001,90.580002,92.250000,79.338943,22235200,NaN
1,7/17/2017,91.820000,91.989998,91.250000,91.389999,78.599312,14374200,-0.932243
2,7/18/2017,90.449997,91.580002,90.320000,91.070000,78.324104,14719400,-0.350140
3,7/19/2017,91.339996,91.620003,91.000000,91.199997,78.435898,11651200,0.142732
4,7/20/2017,91.150002,91.720001,90.900002,91.199997,78.435898,11561700,0.000000
...,...,...,...,...,...,...,...,...
1363,12/12/2022,132.399994,134.649994,131.600006,134.210007,134.210007,8841600,1.551152
1364,12/13/2022,136.889999,137.089996,133.080002,134.080002,134.080002,10025400,-0.096867
1365,12/14/2022,133.779999,135.710007,132.759995,133.410004,133.410004,9966100,-0.499700
1366,12/15/2022,131.149994,132.080002,129.050003,130.100006,130.100006,12087800,-2.481072
1367,12/16/2022,129.149994,129.899994,128.429993,129.289993,129.289993,21126400,-0.622608

In [14]:
stock_df['Daily Returns']=stock_df['Daily Returns'].fillna(0)
stock_df

,Date,Open,High,Low,Close,Adj Close,Volume,Daily Returns
0,7/14/2017,90.809998,92.610001,90.580002,92.250000,79.338943,22235200,0.000000
1,7/17/2017,91.820000,91.989998,91.250000,91.389999,78.599312,14374200,-0.932243
2,7/18/2017,90.449997,91.580002,90.320000,91.070000,78.324104,14719400,-0.350140
3,7/19/2017,91.339996,91.620003,91.000000,91.199997,78.435898,11651200,0.142732
4,7/20/2017,91.150002,91.720001,90.900002,91.199997,78.435898,11561700,0.000000
...,...,...,...,...,...,...,...,...
1363,12/12/2022,132.399994,134.649994,131.600006,134.210007,134.210007,8841600,1.551152
1364,12/13/2022,136.889999,137.089996,133.080002,134.080002,134.080002,10025400,-0.096867
1365,12/14/2022,133.779999,135.710007,132.759995,133.410004,133.410004,9966100,-0.499700
1366,12/15/2022,131.149994,132.080002,129.050003,130.100006,130.100006,12087800,-2.481072
1367,12/16/2022,129.149994,129.899994,128.429993,129.289993,129.289993,21126400,-0.622608

In [15]:
stock_df.describe().round(2)

,Open,High,Low,Close,Adj Close,Volume,Daily Returns
count,1368.00,1368.00,1368.00,1368.00,1368.00,1368.00,1368.00
mean,120.67,121.88,119.46,120.65,112.18,14413609.94,0.05
std,21.82,21.91,21.71,21.81,23.82,6503745.66,1.96
min,81.56,83.75,76.91,79.03,72.58,3220500.00,-14.96
25%,104.73,105.70,103.73,104.76,93.91,10228700.00,-0.83
50%,114.51,115.41,113.44,114.53,102.74,12855450.00,0.00
75%,134.89,136.45,133.94,135.29,128.46,16357600.00,0.96
max,172.71,172.96,170.54,171.78,166.52,54418800.00,18.01

In [16]:
JPM_df=pd.read_csv('JPM.csv')

In [17]:
JPM_df

,Date,Open,High,Low,Close,Adj Close,Volume
0,7/14/2017,90.809998,92.610001,90.580002,92.250000,79.338943,22235200
1,7/17/2017,91.820000,91.989998,91.250000,91.389999,78.599312,14374200
2,7/18/2017,90.449997,91.580002,90.320000,91.070000,78.324104,14719400
3,7/19/2017,91.339996,91.620003,91.000000,91.199997,78.435898,11651200
4,7/20/2017,91.150002,91.720001,90.900002,91.199997,78.435898,11561700
...,...,...,...,...,...,...,...
1363,12/12/2022,132.399994,134.649994,131.600006,134.210007,134.210007,8841600
1364,12/13/2022,136.889999,137.089996,133.080002,134.080002,134.080002,10025400
1365,12/14/2022,133.779999,135.710007,132.759995,133.410004,133.410004,9966100
1366,12/15/2022,131.149994,132.080002,129.050003,130.100006,130.100006,12087800
1367,12/16/2022,129.149994,129.899994,128.429993,129.289993,129.289993,21126400

In [18]:
JPM_df['Daily Return']=JPM_df['Adj Close'].pct_change(1)*100
JPM_df['Daily Return']=JPM_df['Daily Return'].fillna(0)
JPM_df

,Date,Open,High,Low,Close,Adj Close,Volume,Daily Return
0,7/14/2017,90.809998,92.610001,90.580002,92.250000,79.338943,22235200,0.000000
1,7/17/2017,91.820000,91.989998,91.250000,91.389999,78.599312,14374200,-0.932243
2,7/18/2017,90.449997,91.580002,90.320000,91.070000,78.324104,14719400,-0.350140
3,7/19/2017,91.339996,91.620003,91.000000,91.199997,78.435898,11651200,0.142732
4,7/20/2017,91.150002,91.720001,90.900002,91.199997,78.435898,11561700,0.000000
...,...,...,...,...,...,...,...,...
1363,12/12/2022,132.399994,134.649994,131.600006,134.210007,134.210007,8841600,1.551152
1364,12/13/2022,136.889999,137.089996,133.080002,134.080002,134.080002,10025400,-0.096867
1365,12/14/2022,133.779999,135.710007,132.759995,133.410004,133.410004,9966100,-0.499700
1366,12/15/2022,131.149994,132.080002,129.050003,130.100006,130.100006,12087800,-2.481072
1367,12/16/2022,129.149994,129.899994,128.429993,129.289993,129.289993,21126400,-0.622608

In [19]:
JPM_df.isnull().sum()

Date            0
Open            0
High            0
Low             0
Close           0
Adj Close       0
Volume          0
Daily Return    0
dtype: int64

In [20]:
import matplotlib.pyplot as plt

In [24]:
import sys
!{sys.executable} -m pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from seaborn) (1.26.1)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from seaborn) (1.5.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from seaborn) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.1)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

In [25]:
import seaborn as sns

In [27]:
import sys
!{sys.executable} -m pip install plotly

Collecting plotly
  Downloading plotly-6.7.0-py3-none-any.whl.metadata (8.6 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.21.2-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from plotly) (23.1)
Downloading plotly-6.7.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 43.4 MB/s  0:00:00 eta 0:00:01
Downloading narwhals-2.21.2-py3-none-any.whl (451 kB)
Installing collected packages: narwhals, plotly
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [plotly]2m1/2 [plotly]
Successfully installed narwhals-2.21.2 plotly-6.7.0

In [28]:
import plotly.express as px

In [29]:
fig=px.line(title='Amazon.com,Inc.(AMZN) Adjusted closing price [$]')
fig.add_scatter(x=stock_df['Date'], y=stock_df['Adj Close'],name='Adj Close')

In [30]:
def plot_financial_data(df,title):
    fig=px.line(title=title)

    for i in df.columns[1:]:
        fig.add_scatter(x=df['Date'],y=df[i], name=i)
        fig.update_traces(line_width=5)
        fig.update_layout({'plot_bgcolor':"white"})
    fig.show()

In [31]:
stock_df

,Date,Open,High,Low,Close,Adj Close,Volume,Daily Returns
0,7/14/2017,90.809998,92.610001,90.580002,92.250000,79.338943,22235200,0.000000
1,7/17/2017,91.820000,91.989998,91.250000,91.389999,78.599312,14374200,-0.932243
2,7/18/2017,90.449997,91.580002,90.320000,91.070000,78.324104,14719400,-0.350140
3,7/19/2017,91.339996,91.620003,91.000000,91.199997,78.435898,11651200,0.142732
4,7/20/2017,91.150002,91.720001,90.900002,91.199997,78.435898,11561700,0.000000
...,...,...,...,...,...,...,...,...
1363,12/12/2022,132.399994,134.649994,131.600006,134.210007,134.210007,8841600,1.551152
1364,12/13/2022,136.889999,137.089996,133.080002,134.080002,134.080002,10025400,-0.096867
1365,12/14/2022,133.779999,135.710007,132.759995,133.410004,133.410004,9966100,-0.499700
1366,12/15/2022,131.149994,132.080002,129.050003,130.100006,130.100006,12087800,-2.481072
1367,12/16/2022,129.149994,129.899994,128.429993,129.289993,129.289993,21126400,-0.622608

In [37]:
stock_df['Daily Returns']=stock_df['Adj Close'].pct_change(1)*100

In [38]:
stock_df

,Date,Open,High,Low,Close,Adj Close,Volume,Daily Returns
0,7/14/2017,90.809998,92.610001,90.580002,92.250000,79.338943,22235200,NaN
1,7/17/2017,91.820000,91.989998,91.250000,91.389999,78.599312,14374200,-0.932243
2,7/18/2017,90.449997,91.580002,90.320000,91.070000,78.324104,14719400,-0.350140
3,7/19/2017,91.339996,91.620003,91.000000,91.199997,78.435898,11651200,0.142732
4,7/20/2017,91.150002,91.720001,90.900002,91.199997,78.435898,11561700,0.000000
...,...,...,...,...,...,...,...,...
1363,12/12/2022,132.399994,134.649994,131.600006,134.210007,134.210007,8841600,1.551152
1364,12/13/2022,136.889999,137.089996,133.080002,134.080002,134.080002,10025400,-0.096867
1365,12/14/2022,133.779999,135.710007,132.759995,133.410004,133.410004,9966100,-0.499700
1366,12/15/2022,131.149994,132.080002,129.050003,130.100006,130.100006,12087800,-2.481072
1367,12/16/2022,129.149994,129.899994,128.429993,129.289993,129.289993,21126400,-0.622608

In [40]:
plot_financial_data(stock_df.drop(['Volume','Daily Returns'], axis=1),'Amazon.com, Inc.(AMZN) Stock Price [$]')

In [41]:
plot_financial_data(stock_df.iloc[:,[0,5]], 'Amazon.com, Inc. (AMZN) Trading Volume')

In [42]:
plot_financial_data(stock_df.iloc[:,[0,7]], 'Amazon.com, Inc. (AMZN) Percentage Daily Return [%]')

In [43]:
print('this is done!')

this is done!